store/app/__init__.py
from .core import create_app

# from typing import Optional

# from flask import Flask, render_template, request, session  # , url_for
# from flask_babel import Babel
# from flask_debugtoolbar import DebugToolbarExtension
# from werkzeug.middleware.proxy_fix import ProxyFix

# from flask_merchants.core import FlaskMerchantsExtension

# from .database import db, migrations
# from .model import *  # noqa: F403
# # from ...store_orig.modules.storefront.route import storefront_bp
# from .views import ProductView

# merchants = FlaskMerchantsExtension()


# def create_app(settings_file: str | None = None):
#     app = Flask("Store", template_folder="store/templates", static_folder="store/static")
#     app.wsgi_app = ProxyFix(app.wsgi_app, x_for=1, x_proto=1, x_host=1, x_prefix=1)

#     # Configure App, env takes precedence
#     if settings_file:
#         app.config.from_object(settings_file)
#     app.config.from_prefixed_env()

#     # SQLAlchemy&Flask-Migrate
#     db.init_app(app)
#     migrations.init_app(app, db, directory="store/migrations")

#     # Flask-Merchants
#     merchants.init_app(app, db)
#     merchants.add_admin_model(Product, ProductView)  # noqa: F405

#     # Flask-DebugToolbar
#     if app.debug:
#         # toolbar = DebugToolbarExtension()
#         # toolbar.init_app(app)
#         pass

#     # Flask-babel
#     babel = Babel()

#     def get_locale():
#         if request.args.get("lang"):
#             session["lang"] = request.args.get("lang")
#         return session.get("lang", app.config.get("BABEL_DEFAULT_LOCALE"))

#     def get_timezone():
#         return app.config.get("BABEL_DEFAULT_TIMEZONE")

#     babel.init_app(
#         app,
#         locale_selector=get_locale,
#         timezone_selector=get_timezone,
#         default_domain=app.config.get("BABEL_DOMAIN", "merchants"),
#         default_translation_directories=app.config.get("BABEL_DEFAULT_FOLDER", "store/translations"),
#     )

#     @app.context_processor
#     def default_data() -> dict:
#         return {
#             "app_version": "2025.3.1",
#         }

#     # app.register_blueprint(storefront_bp)

#     @app.get("/_storefront/")
#     def _storefront():
#         return render_template("store/storefront-2.html")

#     return app

store/app/apoderado/controller.py
class ApoderadoController:
    def index(self):
        return {"message": "Hello, World!"}

store/app/extensions/__init__.py
from flask_babel import Babel
from flask_mailman import Mail

from flask_merchants.core import FlaskMerchantsExtension

babel = Babel()
mail = Mail()
flask_merchants = FlaskMerchantsExtension()

store/app/pos/routes.py
from flask import Blueprint, jsonify, render_template

from .reader import registra_lectura

pos_bp = Blueprint("pos", __name__)


@pos_bp.route("/", methods=["GET"])
def index():
    return render_template("pos/dashboard.html")


@pos_bp.route("/venta", methods=["GET"])
def venta():
    return render_template("pos/venta.html")


@pos_bp.route("/casino", methods=["GET"])
def casino():
    return render_template("pos/casino.html")


@pos_bp.route("/reader", methods=["GET"])
def reader():
    return render_template("pos/reader.html")


@pos_bp.route("/new-reading/")
@pos_bp.route("/new-reading/<int:qr_data>")
def nueva_lectura(qr_data):
    registra_lectura(qr_data=qr_data)
    return jsonify(qr_data)

store/app/routes.py
from flask import Blueprint, render_template

core_bp = Blueprint("core", __name__)


@core_bp.route("/", methods=["GET"])
def index():
    return render_template("site/index.j2")


@core_bp.route("/buscar", methods=["GET"])
def buscar():
    return render_template("site/resultados.html")


@core_bp.route("/admin", methods=["GET"])
def admin():
    return render_template("seleccion.html")


@core_bp.route("/aiuda", methods=["GET"])
def ayuda():
    return render_template("core/ayuda.html")


@core_bp.route("/configuracion", methods=["GET"])
def configuracion():
    return render_template("core/configuracion.html")

store/app/views.py
from flask_admin.contrib.sqla import ModelView

from flask_merchants.views import AppAdmin


class ProductView(AppAdmin, ModelView):
    name = "Product"
    name_plural = "Products"
    column_list = ["slug", "active", "currency", "price", "extra_attrs"]

store/app/templates/apoderado/abono.html
{% extends "base.html" %}

{% block page_header -%}
<div class="page-header d-print-none text-white">
  <div class="container-xl">
    <div class="row g-2 align-items-center">
      <div class="col">
        <!-- Page pre-title -->
        <h1 class="page-title">Abonar Saldo</h1>
      </div>
    </div>
  </div>
</div>
{% endblock page_header -%}

{% block page_body %}
<main id="content" class="page-body">
  <div class="container-xl">
    <div class="row row-cards">
      <div class="col">
        <div class="row row-cards">
          <div class="col-12">
            <form class="card h-100" action="{{ url_for('apoderado.abonar') }}" method="post">
              <div class="card-header">
                <h3 class="card-title">Abonar</h3>
              </div>
              <div class="card-body">

                <div class="mb-3 row">
                  <label class="col-3 col-form-label required">Monto</label>
                  <div class="col">
                    <input type="number" class="form-control" min="2000" max="100000" placeholder="Monto a Abonar" />
                    <small class="form-hint">Mínimo: <strong>$2.000</strong> - Máximo: <strong>$100.000</strong></small>
                  </div>
                </div>

                <div class="mb-3 row">
                  <label class="col-3 col-form-label required">Forma de Pago</label>
                  <div class="col">
                    <div class="form-selectgroup form-selectgroup-boxes d-flex flex-column">
                      <label class="form-selectgroup-item flex-fill">
                        <input type="radio" name="form-payment" value="khipu" class="form-selectgroup-input" />
                        <div class="form-selectgroup-label d-flex align-items-center p-3">
                          <div class="me-3">
                            <span class="form-selectgroup-check"></span>
                          </div>
                          <div>
                            <span class="payment payment-provider-khalti payment-xs me-2"></span>
                            Transferencia Bancaria via <strong>Khipu</strong>
                          </div>
                        </div>
                      </label>
                      <label class="form-selectgroup-item flex-fill">
                        <input type="radio" name="form-payment" value="flow" class="form-selectgroup-input" />
                        <div class="form-selectgroup-label d-flex align-items-center p-3">
                          <div class="me-3">
                            <span class="form-selectgroup-check"></span>
                          </div>
                          <div>
                            <span class="payment payment-provider-mastercard payment-xs me-2"></span>
                            Tarjetas via <strong>Flow</strong>
                          </div>
                        </div>
                      </label>
                      <label class="form-selectgroup-item flex-fill">
                        <input type="radio" name="form-payment" value="Webpay" class="form-selectgroup-input" checked />
                        <div class="form-selectgroup-label d-flex align-items-center p-3">
                          <div class="me-3">
                            <span class="form-selectgroup-check"></span>
                          </div>
                          <div>
                            <span class="payment payment-provider-payconiq payment-xs me-2"></span>
                            Tarjetas y Billeteras Electrónicas via <strong>Webpay</strong>
                          </div>
                        </div>
                      </label>
                      <label class="form-selectgroup-item flex-fill">
                        <input type="radio" name="form-payment" value="efectivo" class="form-selectgroup-input" />
                        <div class="form-selectgroup-label d-flex align-items-center p-3">
                          <div class="me-3">
                            <span class="form-selectgroup-check"></span>
                          </div>
                          <div>
                            <span class="payment payment-provider-cash-app payment-xs me-2"></span>
                            Efectivo <strong>En el colegio</strong>
                          </div>
                        </div>
                      </label>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card-footer">
                <div class="text-end">
                  <button type="submit" class="btn btn-success">Abonar</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

{% endblock page_body %}

store/app/templates/apoderado/abonos.html
{% extends "base.html" %}

{% block page_header -%}
<div class="page-header d-print-none text-white">
  <div class="container">
    <div class="row align-items-center">
      <div class="col">
        <h1 class="fw-bold m-0">Abonos</h1>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock page_header -%}


{% block page_body %}

<div class="container-xl">
  <div class="row g-3">
    <div class="col">
      <ul class="timeline">
        <li class="timeline-event">
          <div class="timeline-event-icon bg-x-lt">
            <!-- Download SVG icon from http://tabler.io/icons/icon/brand-x -->
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" class="icon icon-1">
              <path d="M4 4l11.733 16h4.267l-11.733 -16z" />
              <path d="M4 20l6.768 -6.768m2.46 -2.46l6.772 -6.772" />
            </svg>
          </div>
          <div class="card timeline-event-card">
            <div class="card-body">
              <div class="text-secondary float-end">10 days ago</div>
              <h4>Abono Web</h4>
              <p class="text-secondary">$10.000</p>
            </div>
          </div>
        </li>
        <li class="timeline-event">
          <div class="timeline-event-icon">
            <!-- Download SVG icon from http://tabler.io/icons/icon/briefcase -->
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" class="icon icon-1">
              <path d="M3 7m0 2a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v9a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2z" />
              <path d="M8 7v-2a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v2" />
              <path d="M12 12l0 .01" />
              <path d="M3 13a20 20 0 0 0 18 0" />
            </svg>
          </div>
          <div class="card timeline-event-card">
            <div class="card-body">
              <div class="text-secondary float-end">2 months ago</div>
              <h4>Abono Web</h4>
              <p class="text-secondary">$15.000</p>
            </div>
          </div>
        </li>
        <li class="timeline-event">
          <div class="timeline-event-icon">
            <!-- Download SVG icon from http://tabler.io/icons/icon/check -->
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" class="icon icon-1">
              <path d="M5 12l5 5l10 -10" />
            </svg>
          </div>
          <div class="card timeline-event-card">
            <div class="card-body">
              <div class="text-secondary float-end">3 months ago</div>
              <h4>Abono POS</h4>
              <p class="text-secondary">$7.000</p>
            </div>
          </div>
        </li>
        <li class="timeline-event">
          <div class="timeline-event-icon bg-facebook-lt">
            <!-- Download SVG icon from http://tabler.io/icons/icon/brand-facebook -->
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" class="icon icon-1">
              <path d="M7 10v4h3v7h4v-7h3l1 -4h-4v-2a1 1 0 0 1 1 -1h3v-4h-3a5 5 0 0 0 -5 5v2h-3" />
            </svg>
          </div>
          <div class="card timeline-event-card">
            <div class="card-body">
              <div class="text-secondary float-end">3 months ago</div>
              <h4>Abono POS</h4>
              <p class="text-secondary">$8.000</p>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
{% endblock page_body %}

store/app/templates/apoderado/wizard-paso2.html
{% extends "base-bare.html" %}

{% block page_body %}
<div class="container py-4">
  <div class="card card-md">
    <div class="hr-text hr-text-center hr-text-spaceless">Datos Alumnos</div>
    <div class="card-body">
      <form>
        <div class="space-y">
          <div>
            <h4>Alumno 1</h4>
          </div>
          <div class="row row-cols-2 g-4">
            <div>
              <label class="form-label"> Nombre </label>
              <input type="text" placeholder="Ingrese nombre y apellido" class="form-control" />
            </div>
            <div>
              <label class="form-label"> Curso </label>
              <div>
                <select class="form-select">
                  <option>1-A</option>
                  <option>2-A</option>
                  <option>3-A</option>
                  <option>4-A</option>
                  <option>5-A</option>
                  <option>6-A</option>
                  <option>7-A</option>
                  <option>8-A</option>
                  <option>I-A</option>
                  <option>II-A</option>
                  <option>III-A</option>
                  <option>IV-A</option>
                </select>
              </div>
            </div>
            <div>
              <label class="form-label"> Edad </label>
              <input type="number" placeholder="Edad" class="form-control" max="19" min="4" />
            </div>
          </div>

          <div class="hr"></div>

          <div>
            <h4>Alumno 2</h4>
          </div>
          <div class="row row-cols-2 g-4">
            <div>
              <label class="form-label"> Nombre </label>
              <input type="text" placeholder="Ingrese nombre y apellido" class="form-control" />
            </div>
            <div>
              <label class="form-label"> Curso </label>
              <div>
                <select class="form-select">
                  <option>1-A</option>
                  <option>2-A</option>
                  <option>3-A</option>
                  <option>4-A</option>
                  <option>5-A</option>
                  <option>6-A</option>
                  <option>7-A</option>
                  <option>8-A</option>
                  <option>I-A</option>
                  <option>II-A</option>
                  <option>III-A</option>
                  <option>IV-A</option>
                </select>
              </div>
            </div>
            <div>
              <label class="form-label"> Edad </label>
              <input type="number" placeholder="Edad" class="form-control" max="19" min="4" />
            </div>
          </div>


        </div>
      </form>
    </div>
  </div>
  <div class="row align-items-center mt-3">
    <div class="col-4">
      <div class="progress progress-1">
        <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 67%" role="progressbar" aria-valuenow="66" aria-valuemin="0" aria-valuemax="100" aria-label="66% Complete">
          <span class="visually-hidden">66% Complete</span>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="btn-list justify-content-end">
        <a href="https://google.cl" class="btn btn-link link-secondary btn-2"> Continuar más tarde </a>
        <a href="{{ url_for('apoderado.wizp3') }}" class="btn btn-primary btn-2"> Continuar </a>
      </div>
    </div>
  </div>
</div>
{% endblock page_body %}

store/app/templates/base-bare.html
<!doctype html>
<html {% block html_attribs %}{% endblock html_attribs %}>
  {%- block html %}

  <head>
    {%- block head %}
    <title>{% block title %}Storefront{{ title|default }}{% endblock title %}</title>

    {%- block metas %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    {%- endblock metas %}

    {% block favicon %}
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='apple-touch-icon.png', v=app_version)}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon-32x32.png', v=app_version)}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon-16x16.png', v=app_version)}}">
    <link rel="manifest" href="{{ url_for('static', filename='site.webmanifest', v=app_version)}}">
    {% endblock favicon %}

    <link href="{{ url_for('static', filename='tabler/css/tabler.css', v=app_version)}}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='tabler/css/tabler-themes.css', v=app_version)}}" rel="stylesheet" />
    <link href="{{ url_for('static', filename='tabler/css/tabler-payments.css', v=app_version)}}" rel="stylesheet" />

    <style>
      @import url("https://rsms.me/inter/inter.css");
    </style>

    {%- block head_styles %}
    {%- endblock head_styles %}

    {%- block head_scripts %}
    {%- endblock head_scripts %}

    {%- endblock head %}
  </head>

  <!-- <body class="layout-fluid"> -->

  <body>
    <div class="page">

      <div class="page-wrapper">

        <!-- BEGIN PAGE HEADER -->
        {% block page_header -%}
        {% endblock page_header -%}
        <!-- END PAGE HEADER -->

        <!-- BEGIN PAGE BODY -->
        <main id="content" class="page-body">
          {% block page_body -%}
          {% endblock page_body -%}
        </main>
        <!-- END PAGE BODY -->

      </div>
    </div>


    <!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
    <script src="{{ url_for('static', filename='tabler/js/tabler.min.js', v=app_version)}}" defer></script>
    <!-- END GLOBAL MANDATORY SCRIPTS -->
    <!-- BEGIN PAGE SCRIPTS -->
    {% block page_scripts -%}
    {% endblock page_scripts -%}
    <!-- END PAGE SCRIPTS -->
  </body>
  {%- endblock html %}

</html>

store/app/templates/pos/reader.html
{% extends "base-pos.html" %}

{% block head_styles %}
<style>
  .section {
    background-color: #ffffff;
    padding: 50px 30px;
    border: 1.5px solid #b2b2b2;
    border-radius: 0.25em;
    box-shadow: 0 20px 25px rgba(0, 0, 0, 0.25);
  }

  #my-qr-reader {
    padding: 20px !important;
    border: 1.5px solid #b2b2b2 !important;
    border-radius: 8px;
  }

  #my-qr-reader img[alt="Info icon"] {
    display: none;
  }

  #my-qr-reader img[alt="Camera based scan"] {
    width: 100px !important;
    height: 100px !important;
  }

  .button {
    padding: 10px 20px;
    border: 1px solid #b2b2b2;
    outline: none;
    border-radius: 0.25em;
    color: white;
    font-size: 15px;
    cursor: pointer;
    margin-top: 15px;
    margin-bottom: 10px;
    background-color: #008000ad;
    transition: 0.3s background-color;
  }

  .button:hover {
    background-color: #008000;
  }

  #html5-qrcode-anchor-scan-type-change {
    text-decoration: none !important;
    color: #1d9bf0;
    width: 250px;
  }

  video {
    width: 100% !important;
    border: 1px solid #b2b2b2 !important;
    border-radius: 0.25em;
  }
</style>
{% endblock head_styles %}

{% block page_header -%}
<div class="page-header d-print-none text-white">
  <div class="container-xl">
    <div class="row g-2 align-items-center">
      <div class="col">
        <!-- Page pre-title -->
        <h1 class="page-title">Reporte Línea 2</h1>
      </div>
    </div>
  </div>
</div>
{% endblock page_header -%}

{% block page_body %}
<div class="container-xl">
  <div class="row row-deck row-cards">
    <div class="col-sm-12 col-lg-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Lectores Linea 2</h3>

        </div>

        <div class="card-body">
          <div id="my-qr-reader" style="width: 250px;">
          </div>
        </div>

      </div>
    </div>

    <div class="col-md-12 col-lg-8">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Ranking Operadores Linea 2</h3>
        </div>
        <div class="card-table table-responsive">
          <table class="table table-vcenter">
            <thead>
              <tr>
                <th>Posicion</th>
                <th>Nombre</th>
                <th>ID</th>

                <th>Cajas 5m</th>
                <th>Cajas 15m</th>
                <th>Cajas 30m</th>

              </tr>
            </thead>
            <tr>
              <td>1</td>
              <td>Juanin Juan Harry</td>
              <td>276454</td>

              <td class="text-secondary">4</td>
              <td class="text-secondary">15</td>
              <td class="text-secondary">39</td>

            </tr>
            <tr>
              <td>2</td>
              <td>Mario Hugo</td>
              <td>276454</td>

              <td class="text-secondary">4</td>
              <td class="text-secondary">15</td>
              <td class="text-secondary">39</td>

            </tr>
            <tr>
              <td>3</td>
              <td>Mico el Micofono</td>
              <td>276454</td>

              <td class="text-secondary">4</td>
              <td class="text-secondary">15</td>
              <td class="text-secondary">39</td>

            </tr>
            <tr>
              <td>4</td>
              <td>Freddy Turbina</td>
              <td>427685</td>

              <td class="text-secondary">4</td>
              <td class="text-secondary">15</td>
              <td class="text-secondary">39</td>
            </tr>
            <tr>
              <td>5</td>
              <td>Guaripolo</td>
              <td>345783</td>

              <td class="text-secondary">4</td>
              <td class="text-secondary">15</td>
              <td class="text-secondary">39</td>
            </tr>
          </table>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-lg-4">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Ultimas lecturas Linea 2</h3>
        </div>
        <div class="card-body">
          <ul id="lista-lecturas">
            <li>Caja: 100434565 - Operador: 276454</li>
            <li>Caja: 100434568 - Operador: 427685</li>
            <li>Caja: 100434566 - Operador: 345783</li>
            <li>Caja: 100434563 - Operador: 276454</li>
            <li>Caja: 100434569 - Operador: 276454</li>
            <li>Caja: 100434567 - Operador: 345783</li>
            <li>Caja: 100434564 - Operador: 276454</li>
            <li>Caja: 100434562 - Operador: 345783</li>
            <li>Caja: 100434560 - Operador: 276454</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock page_body -%}


{% block page_scripts -%}
<script src="https://unpkg.com/html5-qrcode@2.3.8/html5-qrcode.min.js"></script>

<script>
  // script.js file

  function read(id) {
    let xhr = new XMLHttpRequest();
    let number = Math.random() * 10000
    let url = '{{ url_for('pos.nueva_lectura') }}/' + id + "?q=" + number;
    xhr.open("GET", url, true);

    xhr.onreadystatechange = function () {
      if (this.readyState == 4 && this.status == 200) {
        console.log(this.responseText);
      }
    }
    xhr.send();
  }

  function domReady(fn) {
    if (
      document.readyState === "complete" ||
      document.readyState === "interactive"
    ) {
      setTimeout(fn, 1000);
    } else {
      document.addEventListener("DOMContentLoaded", fn);
    }
  }

  domReady(function () {

    // If found you qr code
    function onScanSuccess(decodeText, decodeResult) {
      //alert("You Qr is : " + decodeText, decodeResult);
      read(decodeText)
    }

    let htmlscanner = new Html5QrcodeScanner(
      "my-qr-reader",
      { fps: 15, qrbos: 250, supportedScanTypes: [Html5QrcodeScanType.SCAN_TYPE_CAMERA] }
    );
    htmlscanner.render(onScanSuccess);
  });
</script>
{% endblock page_scripts -%}

store/app/templates/seleccion.html
{% extends "base-bare.html" %}

{% block page_body %}
<main id="content" class="page-body">
  <div class="container-xl">
    <div class="row row-cards">
      <div class="col-sm-6 col-lg-3">
        <div class="card card-md">
          <div class="ribbon ribbon-top ribbon-bookmark bg-green">
            <!-- Download SVG icon from http://tabler.io/icons/icon/star -->
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" class="icon icon-3">
              <path d="M12 17.75l-6.172 3.245l1.179 -6.873l-5 -4.867l6.9 -1l3.086 -6.253l3.086 6.253l6.9 1l-5 4.867l1.179 6.873z" />
            </svg>
          </div>
          <div class="card-body text-center">
            <div class="text-uppercase text-secondary font-weight-medium">Data Manager</div>
            <div class="display-5 fw-bold my-3">&nbsp;</div>
            <ul class="list-unstyled lh-lg">
              <li><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" class="icon me-1 text-success icon-2">
                  <path d="M5 12l5 5l10 -10" />
                </svg>Base de datos</li>
            </ul>
            <div class="text-center mt-4">
              <a href="{{ url_for('admin.index')}}" class="btn btn-green w-100">Abrir Data Manager</a>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-lg-3">
        <div class="card card-md">
          <div class="card-body text-center">
            <div class="text-uppercase text-secondary font-weight-medium">POS</div>
            <div class="display-5 fw-bold my-3">&nbsp;</div>
            <ul class="list-unstyled lh-lg">
              <li><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" class="icon me-1 text-success icon-2">
                  <path d="M5 12l5 5l10 -10" />
                </svg>POS para Ventas</li>
              <li><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" class="icon me-1 text-success icon-2">
                  <path d="M5 12l5 5l10 -10" />
                </svg>POS para Canjes</li>
              <li><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" class="icon me-1 text-success icon-2">
                  <path d="M5 12l5 5l10 -10" />
                </svg>Registro de productos</li>
            </ul>
            <div class="text-center mt-4">
              <a href="{{ url_for('pos.index')}}" class="btn btn-green w-100">Abrir App POS</a>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-6 col-lg-3">
        <div class="card card-md">
          <div class="card-body text-center">
            <div class="text-uppercase text-secondary font-weight-medium">Apoderados</div>
            <div class="display-5 fw-bold my-3">&nbsp;</div>
            <ul class="list-unstyled lh-lg">
              <li><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" class="icon me-1 text-success icon-2">
                  <path d="M5 12l5 5l10 -10" />
                </svg>Abonos (Creacion, Historial)</li>
              <li><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" class="icon me-1 text-success icon-2">
                  <path d="M5 12l5 5l10 -10" />
                </svg>Menu Semanal y productos del cafe</li>
              <li><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false" class="icon me-1 text-success icon-2">
                  <path d="M5 12l5 5l10 -10" />
                </svg>Configurar Restricciones y Limites</li>
            </ul>
            <div class="text-center mt-4">
              <a href="{{ url_for('apoderado.index')}}" class="btn btn-green w-100">Abrir App Apoderados</a>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</main>
{% endblock page_body %}